version: '2.2'
services:
  cerebro:
    image: lmenezes/cerebro:0.8.3
    container_name: cerebro
    ports:
      - "9000:9000"
    command:
      - -Dhosts.0.host=http://192.168.1.137:9200
    networks:
      - elastic
  logstash:
    image: docker.elastic.co/logstash/logstash:7.8.0
    container_name: logstash
    volumes:
      - /data/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - /data/logstash.yml:/usr/share/logstash/config/logstash.yml
      - /data/movies.csv:/data/movies.csv
    ports:
      - 5044:5044
    networks:
      - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0
    container_name: kibana7
    environment:
      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
    ports:
      - "5601:5601"
    environment:
      SERVER_NAME: kibana.basicfinder.com
      ELASTICSEARCH_USERNAME: "kibana"
      ELASTICSEARCH_PASSWORD: '"abcd1234"'
    volumes:
      - /data/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elastic
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: elasticsearch
    environment:
      - node.name=es01
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /data:/usr/share/elasticsearch/data
      - /data/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
